//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWebMyPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        public PhieuNhap()
        {
            this.CT_PhieuNhap = new HashSet<CT_PhieuNhap>();
        }
    
        public string MaPhieuNhap { get; set; }
        public string MaNhanVien { get; set; }
        public string MaNhaCungCap { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<double> TongTien { get; set; }
        public string GhiCHu { get; set; }
    
        public virtual ICollection<CT_PhieuNhap> CT_PhieuNhap { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
